Specifically require notebook
This is an attempt to fix the CI failures, which have error message
```python
      from notebook.nbextensions import (
  ModuleNotFoundError: No module named 'notebook.nbextensions'
```